In [1]:
#Import Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer  #    SimpleImputer fill NA values for multiple columns
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet
import matplotlib.pyplot as plt
from sklearn.preprocessing import OrdinalEncoder#for encoding purpose use for encoding independet feature/column working same as OHE
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/aishwaryamate/Datasets/main/cars.csv')
df

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,13495
1,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,16500
2,1,?,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154,19,26,16500
3,2,164,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102,24,30,13950
4,2,164,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114,23,28,16845
201,-1,95,volvo,gas,sedan,rwd,front,68.8,55.5,ohc,141,160,19,25,19045
202,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohcv,173,134,18,23,21485
203,-1,95,volvo,diesel,sedan,rwd,front,68.9,55.5,ohc,145,106,26,27,22470
204,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114,19,25,22625

# EDA

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   body-style         205 non-null    object
 5   drive-wheels       205 non-null    object
 6   engine-location    205 non-null    object
 7   width              205 non-null    float64
 8   height             205 non-null    float64
 9   engine-type        205 non-null    object
 10  engine-size        205 non-null    int64
 11  horsepower         205 non-null    object
 12  city-mpg           205 non-null    int64
 13  highway-mpg        205 non-null    int64
 14  price              205 non-null    int64
dtypes: float64(2), int64(5), object(8)
memory usage: 24.2+ KB

In [4]:
df.isna().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
body-style           0
drive-wheels         0
engine-location      0
width                0
height               0
engine-type          0
engine-size          0
horsepower           0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [5]:
df['normalized-losses'].value_counts()

?      41
161    11
91      8
150     7
134     6
128     6
104     6
85      5
94      5
65      5
102     5
74      5
168     5
103     5
95      5
106     4
93      4
118     4
148     4
122     4
83      3
125     3
154     3
115     3
137     3
101     3
119     2
87      2
89      2
192     2
197     2
158     2
81      2
188     2
194     2
153     2
129     2
108     2
110     2
164     2
145     2
113     2
256     1
107     1
90      1
231     1
142     1
121     1
78      1
98      1
186     1
77      1
Name: normalized-losses, dtype: int64

In [6]:
df[df['horsepower']=='?']

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
130,0,?,renault,gas,wagon,fwd,front,66.5,55.2,ohc,132,?,23,31,9295
131,2,?,renault,gas,hatchback,fwd,front,66.6,50.5,ohc,132,?,23,31,9895

In [4]:
df.replace('?', np.nan, inplace=True)   # np.nan replace ? with NA values

In [8]:
df.isna().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
body-style            0
drive-wheels          0
engine-location       0
width                 0
height                0
engine-type           0
engine-size           0
horsepower            2
city-mpg              0
highway-mpg           0
price                 0
dtype: int64

In [5]:
df

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,13495
1,3,NaN,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,16500
2,1,NaN,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154,19,26,16500
3,2,164,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102,24,30,13950
4,2,164,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114,23,28,16845
201,-1,95,volvo,gas,sedan,rwd,front,68.8,55.5,ohc,141,160,19,25,19045
202,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohcv,173,134,18,23,21485
203,-1,95,volvo,diesel,sedan,rwd,front,68.9,55.5,ohc,145,106,26,27,22470
204,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114,19,25,22625

In [6]:
df['normalized-losses']

0      NaN
1      NaN
2      NaN
3      164
4      164
      ...
200     95
201     95
202     95
203     95
204     95
Name: normalized-losses, Length: 205, dtype: object

In [10]:
df.dtypes

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
body-style            object
drive-wheels          object
engine-location       object
width                float64
height               float64
engine-type           object
engine-size            int64
horsepower            object
city-mpg               int64
highway-mpg            int64
price                  int64
dtype: object

In [7]:
si = SimpleImputer(strategy='median')

In [8]:
df

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,13495
1,3,NaN,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,16500
2,1,NaN,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154,19,26,16500
3,2,164,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102,24,30,13950
4,2,164,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114,23,28,16845
201,-1,95,volvo,gas,sedan,rwd,front,68.8,55.5,ohc,141,160,19,25,19045
202,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohcv,173,134,18,23,21485
203,-1,95,volvo,diesel,sedan,rwd,front,68.9,55.5,ohc,145,106,26,27,22470
204,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114,19,25,22625

In [15]:
df.iloc[:,[1,11]]

    normalized-losses horsepower
0                 NaN        111
1                 NaN        111
2                 NaN        154
3                 164        102
4                 164        115
..                ...        ...
200                95        114
201                95        160
202                95        134
203                95        106
204                95        114

[205 rows x 2 columns]

In [16]:
df[['normalized-losses','horsepower']]

    normalized-losses horsepower
0                 NaN        111
1                 NaN        111
2                 NaN        154
3                 164        102
4                 164        115
..                ...        ...
200                95        114
201                95        160
202                95        134
203                95        106
204                95        114

[205 rows x 2 columns]

In [18]:
df.loc[:,['normalized-losses','horsepower']]

    normalized-losses horsepower
0                 NaN        111
1                 NaN        111
2                 NaN        154
3                 164        102
4                 164        115
..                ...        ...
200                95        114
201                95        160
202                95        134
203                95        106
204                95        114

[205 rows x 2 columns]

In [9]:
df.iloc[:,[1,11]]  = si.fit_transform(df.iloc[:,[1,11]])

In [10]:
df.isna().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
body-style           0
drive-wheels         0
engine-location      0
width                0
height               0
engine-type          0
engine-size          0
horsepower           0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [11]:
df.select_dtypes([int,float])

,symboling,normalized-losses,width,height,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,115.0,64.1,48.8,130,111.0,21,27,13495
1,3,115.0,64.1,48.8,130,111.0,21,27,16500
2,1,115.0,65.5,52.4,152,154.0,19,26,16500
3,2,164.0,66.2,54.3,109,102.0,24,30,13950
4,2,164.0,66.4,54.3,136,115.0,18,22,17450
...,...,...,...,...,...,...,...,...,...
200,-1,95.0,68.9,55.5,141,114.0,23,28,16845
201,-1,95.0,68.8,55.5,141,160.0,19,25,19045
202,-1,95.0,68.9,55.5,173,134.0,18,23,21485
203,-1,95.0,68.9,55.5,145,106.0,26,27,22470
204,-1,95.0,68.9,55.5,141,114.0,19,25,22625

In [27]:
df

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,115.0,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111.0,21,27,13495
1,3,115.0,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111.0,21,27,16500
2,1,115.0,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154.0,19,26,16500
3,2,164.0,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102.0,24,30,13950
4,2,164.0,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115.0,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114.0,23,28,16845
201,-1,95.0,volvo,gas,sedan,rwd,front,68.8,55.5,ohc,141,160.0,19,25,19045
202,-1,95.0,volvo,gas,sedan,rwd,front,68.9,55.5,ohcv,173,134.0,18,23,21485
203,-1,95.0,volvo,diesel,sedan,rwd,front,68.9,55.5,ohc,145,106.0,26,27,22470
204,-1,95.0,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114.0,19,25,22625

# Encoding

In [ ]:
#Selecting only categorical columns

In [12]:
df.select_dtypes(object).columns

Index(['make', 'fuel-type', 'body-style', 'drive-wheels', 'engine-location',
       'engine-type'],
      dtype='object')

In [13]:
cat_cols = df.select_dtypes(object).columns
cat_cols

Index(['make', 'fuel-type', 'body-style', 'drive-wheels', 'engine-location',
       'engine-type'],
      dtype='object')

In [38]:
df[cat_cols]

,make,fuel-type,body-style,drive-wheels,engine-location,engine-type
0,alfa-romero,gas,convertible,rwd,front,dohc
1,alfa-romero,gas,convertible,rwd,front,dohc
2,alfa-romero,gas,hatchback,rwd,front,ohcv
3,audi,gas,sedan,fwd,front,ohc
4,audi,gas,sedan,4wd,front,ohc
...,...,...,...,...,...,...
200,volvo,gas,sedan,rwd,front,ohc
201,volvo,gas,sedan,rwd,front,ohc
202,volvo,gas,sedan,rwd,front,ohcv
203,volvo,diesel,sedan,rwd,front,ohc
204,volvo,gas,sedan,rwd,front,ohc

In [14]:
oe = OrdinalEncoder()

df[cat_cols] = oe.fit_transform(df[cat_cols])

In [15]:
df

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,115.0,0.0,1.0,0.0,2.0,0.0,64.1,48.8,0.0,130,111.0,21,27,13495
1,3,115.0,0.0,1.0,0.0,2.0,0.0,64.1,48.8,0.0,130,111.0,21,27,16500
2,1,115.0,0.0,1.0,2.0,2.0,0.0,65.5,52.4,5.0,152,154.0,19,26,16500
3,2,164.0,1.0,1.0,3.0,1.0,0.0,66.2,54.3,3.0,109,102.0,24,30,13950
4,2,164.0,1.0,1.0,3.0,0.0,0.0,66.4,54.3,3.0,136,115.0,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,21.0,1.0,3.0,2.0,0.0,68.9,55.5,3.0,141,114.0,23,28,16845
201,-1,95.0,21.0,1.0,3.0,2.0,0.0,68.8,55.5,3.0,141,160.0,19,25,19045
202,-1,95.0,21.0,1.0,3.0,2.0,0.0,68.9,55.5,5.0,173,134.0,18,23,21485
203,-1,95.0,21.0,0.0,3.0,2.0,0.0,68.9,55.5,3.0,145,106.0,26,27,22470
204,-1,95.0,21.0,1.0,3.0,2.0,0.0,68.9,55.5,3.0,141,114.0,19,25,22625

In [16]:
df.dtypes

symboling              int64
normalized-losses    float64
make                 float64
fuel-type            float64
body-style           float64
drive-wheels         float64
engine-location      float64
width                float64
height               float64
engine-type          float64
engine-size            int64
horsepower           float64
city-mpg               int64
highway-mpg            int64
price                  int64
dtype: object

# Model building

In [17]:
x = df.iloc[:,:-1]
y = df['price']

In [18]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3, random_state=1)

In [19]:
lr = LinearRegression()
lr.fit(xtrain,ytrain)
ypred = lr.predict(xtest)
ypred

array([ 6114.11943789,  6899.1299745 ,  5179.12129606,  6534.49022809,
        9125.91144455, 26384.12259969,  7406.15558344,   895.58275157,
        5172.9291232 , 13513.24663171, 15407.85345859, 14421.55136235,
       16418.89788598, 11145.35574554, 16463.66533212, 13896.61774947,
        7335.98228673,  8845.0632645 , 10862.74899523,  7555.18709439,
       11006.99145217,  6830.04912601, 13638.73999814,  6363.9621527 ,
       13732.90563984,  8845.0632645 , 15040.20874209,  6544.19455256,
        4706.60204753,  9314.78618354,  8128.3940468 , 14321.0634702 ,
       25655.82279003, 11987.68138692, 19723.90650907,  6557.53154026,
        8154.91470876, 30658.97297566,  9834.8439003 , 16923.44920496,
        6520.66900847, 20194.14945986,  7692.55861481,  8459.52258636,
        8670.04245903,  7166.21791784, 40486.41308962,  7569.40057796,
       17170.51789287, 18954.92930717, 26190.76513016, 16914.80136249,
       21856.35461232,  6225.96759922, 13090.60124574,  7294.0335782 ,
       11026.86555708, 11260.61809773, 22672.43646491,  8292.10615643,
        9523.00301461, 11224.3749507 ])

In [20]:
lr.intercept_ # incercept(c)

-64935.11357978258

In [21]:
lr.coef_  # slop/weight (m)

array([ 5.71727164e+01,  4.76320989e-01, -2.01309566e+02, -6.22705136e+02,
       -1.63712110e+02,  1.88863899e+03,  1.63884484e+04,  7.90632094e+02,
        3.61221503e+02,  2.81207534e+02,  9.82290864e+01, -1.06474945e+01,
        3.08435166e+02, -4.17126915e+02])

In [22]:
lr.score(xtrain,ytrain), lr.score(xtest,ytest)  # Accuracy

(0.8504229026078214, 0.7964854785429526)

# Lasso

In [23]:
l1 = Lasso()
l1.fit(xtrain,ytrain)
l1.score(xtrain,ytrain), l1.score(xtest,ytest)

(0.8504215478243033, 0.796661521157569)

In [24]:
l1.coef_

array([ 5.70766693e+01,  4.67141700e-01, -2.01139953e+02, -6.14206970e+02,
       -1.64751649e+02,  1.88558824e+03,  1.63181959e+04,  7.88680118e+02,
        3.61783500e+02,  2.81248690e+02,  9.83193653e+01, -1.05310631e+01,
        3.07274772e+02, -4.15725804e+02])

# Hyperparameter Tuning

In [25]:
for i in range(100,200):
    l1 = Lasso(alpha=i)
    l1.fit(xtrain,ytrain)
    print(f"Alpha: {i} Train : {l1.score(xtrain,ytrain)} Test: {l1.score(xtest,ytest)}")

Alpha: 100 Train : 0.8372483974026498 Test: 0.8092040910955611
Alpha: 101 Train : 0.836989922954141 Test: 0.8092979610738258
Alpha: 102 Train : 0.8367288785613758 Test: 0.8093910017461712
Alpha: 103 Train : 0.8364651676681871 Test: 0.8094832684251523
Alpha: 104 Train : 0.8361989818307349 Test: 0.8095746503624814
Alpha: 105 Train : 0.8359302253870347 Test: 0.8096652035299016
Alpha: 106 Train : 0.8356588978359675 Test: 0.8097549282309099
Alpha: 107 Train : 0.8353849991129143 Test: 0.8098438245155563
Alpha: 108 Train : 0.8351084257059387 Test: 0.8099319454841271
Alpha: 109 Train : 0.8348293842179737 Test: 0.810019184028544
Alpha: 110 Train : 0.8345477714936766 Test: 0.8101055942385991
Alpha: 111 Train : 0.8342635877040371 Test: 0.8101911760417997
Alpha: 112 Train : 0.8339767222137542 Test: 0.810275981362897
Alpha: 113 Train : 0.8336873954613209 Test: 0.8103599056262563
Alpha: 114 Train : 0.8333954973355284 Test: 0.810443001666504
Alpha: 115 Train : 0.8331010276993127 Test: 0.8105252695475362
Alpha: 116 Train : 0.8328038691204882 Test: 0.8106067595950118
Alpha: 117 Train : 0.8325042561318754 Test: 0.8106873701557593
Alpha: 118 Train : 0.8322020717101932 Test: 0.8107671525374285
Alpha: 119 Train : 0.8318973159092649 Test: 0.8108461067199922
Alpha: 120 Train : 0.8315898643306087 Test: 0.8109242812985722
Alpha: 121 Train : 0.831279966029459 Test: 0.8110015778648527
Alpha: 122 Train : 0.8309674969080166 Test: 0.8110780460553539
Alpha: 123 Train : 0.8306523257994232 Test: 0.8111537336006446
Alpha: 124 Train : 0.8303347149155726 Test: 0.8112285440004983
Alpha: 125 Train : 0.8300145320017066 Test: 0.8113025265087271
Alpha: 126 Train : 0.8296917792068186 Test: 0.8113756803829956
Alpha: 127 Train : 0.8293663164754228 Test: 0.8114480518748999
Alpha: 128 Train : 0.8290384195488705 Test: 0.8115195488665821
Alpha: 129 Train : 0.8287079533571842 Test: 0.8115902170896443
Alpha: 130 Train : 0.8283747703082014 Test: 0.8116601017520375
Alpha: 131 Train : 0.8280391586533504 Test: 0.8117291135142943
Alpha: 132 Train : 0.8277009785176217 Test: 0.8117972963383393
Alpha: 133 Train : 0.8273600743513216 Test: 0.8118646943166663
Alpha: 134 Train : 0.827016751920332 Test: 0.8119312197807059
Alpha: 135 Train : 0.8266708579462199 Test: 0.8119969172586021
Alpha: 136 Train : 0.8263223897906082 Test: 0.8120617874347758
Alpha: 137 Train : 0.8259711936341725 Test: 0.8121258693292266
Alpha: 138 Train : 0.8256175865009793 Test: 0.8121890813322457
Alpha: 139 Train : 0.8252612405575874 Test: 0.8122515055400706
Alpha: 140 Train : 0.8249024913515862 Test: 0.8123130602354285
Alpha: 141 Train : 0.8245411708666055 Test: 0.8123737869230407
Alpha: 142 Train : 0.8241771102161817 Test: 0.8124337227741056
Alpha: 143 Train : 0.8238106530253966 Test: 0.8124927911020219
Alpha: 144 Train : 0.8234416172134692 Test: 0.8125510330332
Alpha: 145 Train : 0.8230698280784812 Test: 0.8126084835163166
Alpha: 146 Train : 0.8226956503354529 Test: 0.8126650681694727
Alpha: 147 Train : 0.8223189013367542 Test: 0.8127208248289376
Alpha: 148 Train : 0.8219393940513868 Test: 0.8127757876072302
Alpha: 149 Train : 0.8215575086176152 Test: 0.812829886091909
Alpha: 150 Train : 0.8211730520262539 Test: 0.8128831566524963
Alpha: 151 Train : 0.820785829557052 Test: 0.8129356313528255
Alpha: 152 Train : 0.8203962392797491 Test: 0.8129872435786123
Alpha: 153 Train : 0.8200038659827094 Test: 0.8130380604531804
Alpha: 154 Train : 0.8196091274468165 Test: 0.813088016748596
Alpha: 155 Train : 0.8192116048584223 Test: 0.8131371754207155
Alpha: 156 Train : 0.818811725601232 Test: 0.8131854746070425
Alpha: 157 Train : 0.8184092752900354 Test: 0.8132329459427778
Alpha: 158 Train : 0.8180040340448276 Test: 0.8132796171081449
Alpha: 159 Train : 0.8175964432833528 Test: 0.8133254313927007
Alpha: 160 Train : 0.8171860531186914 Test: 0.8133704442145946
Alpha: 161 Train : 0.8167733221546688 Test: 0.813414601485618
Alpha: 162 Train : 0.8163577832181739 Test: 0.8134579558972019
Alpha: 163 Train : 0.8159399130313314 Test: 0.8135004561259737
Alpha: 164 Train : 0.8155192326252293 Test: 0.8135421513909358
Alpha: 165 Train : 0.8150962240434019 Test: 0.813582994628872
Alpha: 166 Train : 0.8146706427093287 Test: 0.8136230103114317
Alpha: 167 Train : 0.8142422390421418 Test: 0.8136622185802581
Alpha: 168 Train : 0.8138115184156172 Test: 0.8137005774315418
Alpha: 169 Train : 0.8133779670184813 Test: 0.813738127152358
Alpha: 170 Train : 0.812942107429732 Test: 0.8137748292356426
Alpha: 171 Train : 0.8125034086683016 Test: 0.8138107203716055
Alpha: 172 Train : 0.8120624104546716 Test: 0.8138457657584284
Alpha: 173 Train : 0.8116185647484577 Test: 0.8138799982828286
Alpha: 174 Train : 0.8111721398138243 Test: 0.8139134011642213
Alpha: 175 Train : 0.8107234361496891 Test: 0.8139459609474126
Alpha: 176 Train : 0.8102718648859879 Test: 0.8139777051490644
Alpha: 177 Train : 0.8098180239059948 Test: 0.8140086084473979
Alpha: 178 Train : 0.8093613132661213 Test: 0.8140386937712968
Alpha: 179 Train : 0.8089023413382919 Test: 0.8140679405535107
Alpha: 180 Train : 0.8084404898252786 Test: 0.8140963672263578
Alpha: 181 Train : 0.8079760625391162 Test: 0.8141239640881857
Alpha: 182 Train : 0.807509389733142 Test: 0.8141507260035141
Alpha: 183 Train : 0.8070398161300381 Test: 0.8141766644353041
Alpha: 184 Train : 0.8065680080542683 Test: 0.8142017704223896
Alpha: 185 Train : 0.8060932933491103 Test: 0.8142260504255305
Alpha: 186 Train : 0.8056160025244099 Test: 0.814249500599942
Alpha: 187 Train : 0.8051364964854255 Test: 0.814272122341565
Alpha: 188 Train : 0.8046540668179516 Test: 0.8142939142513761
Alpha: 189 Train : 0.804169062241406 Test: 0.8143148763571932
Alpha: 190 Train : 0.8036814832401014 Test: 0.8143350086553349
Alpha: 191 Train : 0.803191727560556 Test: 0.8143543185997576
Alpha: 192 Train : 0.8026990258705379 Test: 0.8143727932940248
Alpha: 193 Train : 0.8022037529436448 Test: 0.8143904384269915
Alpha: 194 Train : 0.801705909538015 Test: 0.8144072540570483
Alpha: 195 Train : 0.8012054966196824 Test: 0.8144232402636585
Alpha: 196 Train : 0.800702515179387 Test: 0.8144383971441084
Alpha: 197 Train : 0.8001973998845259 Test: 0.8144527419474971
Alpha: 198 Train : 0.7996892947832843 Test: 0.8144662423958203
Alpha: 199 Train : 0.799178624196061 Test: 0.8144789139191477

In [26]:
l1 = Lasso(alpha=175)
l1.fit(xtrain,ytrain)
l1.score(xtrain,ytrain), l1.score(xtest,ytest)

(0.8107234361496891, 0.8139459609474126)

In [27]:
l1.coef_    # so there are two columns which we can remove so this is calles feature selection

array([  26.15091464,   -0.        , -173.02547787,   -0.        ,
       -363.80743898, 1247.84193718, 3867.709301  ,  391.04314711,
        451.57194036,  297.35122938,  113.32977728,   11.00742675,
         70.90090498, -160.35202828])

In [28]:
xtrain.columns  # so we can remove  normalized-losses,fuel-type or else these columns are no that much important

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'body-style',
       'drive-wheels', 'engine-location', 'width', 'height', 'engine-type',
       'engine-size', 'horsepower', 'city-mpg', 'highway-mpg'],
      dtype='object')

# Ridge

In [29]:
l2 = Ridge()

l2.fit(xtrain,ytrain)
l2.score(xtrain,ytrain), l2.score(xtest,ytest)

(0.8435840853399224, 0.8075632224690538)

In [30]:
for i in range(1,100):
    l2 = Ridge(alpha=i)
    l2.fit(xtrain,ytrain)
    print(f"Alpha: {i} Train: {l2.score(xtrain,ytrain)} Test: {l2.score(xtest,ytest)}")

Alpha: 1 Train: 0.8435840853399224 Test: 0.8075632224690538
Alpha: 2 Train: 0.8356695734845092 Test: 0.8112192014374258
Alpha: 3 Train: 0.8296379623431074 Test: 0.8129299663310144
Alpha: 4 Train: 0.8250699092246865 Test: 0.8138839096972439
Alpha: 5 Train: 0.8215093087765017 Test: 0.8144682684596017
Alpha: 6 Train: 0.8186486103834849 Test: 0.8148435627265231
Alpha: 7 Train: 0.8162882573020809 Test: 0.8150880725612085
Alpha: 8 Train: 0.8142964263180523 Test: 0.8152447305071581
Alpha: 9 Train: 0.8125835227290971 Test: 0.8153392574436445
Alpha: 10 Train: 0.8110868722186455 Test: 0.8153881483263246
Alpha: 11 Train: 0.8097614513602518 Test: 0.815402561027951
Alpha: 12 Train: 0.8085741366835053 Test: 0.8153903693701573
Alpha: 13 Train: 0.8075000372738096 Test: 0.8153573212892012
Alpha: 14 Train: 0.8065200924084591 Test: 0.8153077294072231
Alpha: 15 Train: 0.8056194580416448 Test: 0.8152449025615437
Alpha: 16 Train: 0.804786398073303 Test: 0.8151714264843273
Alpha: 17 Train: 0.804011506518747 Test: 0.8150893527689591
Alpha: 18 Train: 0.8032871514648678 Test: 0.8150003299437465
Alpha: 19 Train: 0.8026070707304607 Test: 0.8149056967781804
Alpha: 20 Train: 0.8019660732378707 Test: 0.8148065502246252
Alpha: 21 Train: 0.8013598153077788 Test: 0.8147037958811021
Alpha: 22 Train: 0.8007846308878104 Test: 0.8145981861304739
Alpha: 23 Train: 0.8002374011637662 Test: 0.8144903494117508
Alpha: 24 Train: 0.7997154533085166 Test: 0.8143808129927237
Alpha: 25 Train: 0.7992164810518412 Test: 0.8142700209017135
Alpha: 26 Train: 0.7987384817763887 Test: 0.814158348199973
Alpha: 27 Train: 0.7982797062609372 Test: 0.8140461124511115
Alpha: 28 Train: 0.7978386181969567 Test: 0.8139335830177277
Alpha: 29 Train: 0.7974138613263304 Test: 0.8138209886554861
Alpha: 30 Train: 0.7970042325726074 Test: 0.8137085237599928
Alpha: 31 Train: 0.796608659923398 Test: 0.8135963535381272
Alpha: 32 Train: 0.7962261841073034 Test: 0.8134846183137234
Alpha: 33 Train: 0.795855943322788 Test: 0.8133734371313502
Alpha: 34 Train: 0.7954971604380747 Test: 0.8132629107871042
Alpha: 35 Train: 0.7951491322043275 Test: 0.8131531243887079
Alpha: 36 Train: 0.7948112201189454 Test: 0.8130441495267424
Alpha: 37 Train: 0.7944828426489629 Test: 0.8129360461229017
Alpha: 38 Train: 0.7941634685815293 Test: 0.8128288640086807
Alpha: 39 Train: 0.7938526113131443 Test: 0.8127226442780506
Alpha: 40 Train: 0.7935498239245844 Test: 0.8126174204498454
Alpha: 41 Train: 0.7932546949164723 Test: 0.8125132194693003
Alpha: 42 Train: 0.7929668445028013 Test: 0.8124100625731355
Alpha: 43 Train: 0.7926859213776737 Test: 0.8123079660384829
Alpha: 44 Train: 0.7924115998850196 Test: 0.8122069418326153
Alpha: 45 Train: 0.7921435775328082 Test: 0.8121069981777136
Alpha: 46 Train: 0.7918815728028477 Test: 0.8120081400426531
Alpha: 47 Train: 0.7916253232151242 Test: 0.8119103695719458
Alpha: 48 Train: 0.7913745836120686 Test: 0.811813686460422
Alpha: 49 Train: 0.7911291246334806 Test: 0.8117180882809591
Alpha: 50 Train: 0.7908887313572603 Test: 0.8116235707715006
Alpha: 51 Train: 0.7906532020847592 Test: 0.8115301280866845
Alpha: 52 Train: 0.7904223472526622 Test: 0.8114377530186675
Alpha: 53 Train: 0.7901959884558676 Test: 0.8113464371910789
Alpha: 54 Train: 0.7899739575680172 Test: 0.8112561712294912
Alpha: 55 Train: 0.7897560959481499 Test: 0.8111669449113404
Alpha: 56 Train: 0.7895422537235102 Test: 0.811078747297838
Alpha: 57 Train: 0.7893322891398646 Test: 0.8109915668500711
Alpha: 58 Train: 0.7891260679717906 Test: 0.8109053915312066
Alpha: 59 Train: 0.7889234629863807 Test: 0.8108202088964674
Alpha: 60 Train: 0.7887243534546109 Test: 0.8107360061723384
Alpha: 61 Train: 0.7885286247053472 Test: 0.8106527703262636
Alpha: 62 Train: 0.7883361677175604 Test: 0.8105704881279607
Alpha: 63 Train: 0.788146878746856 Test: 0.8104891462033195
Alpha: 64 Train: 0.7879606589828784 Test: 0.8104087310817414
Alpha: 65 Train: 0.7877774142345472 Test: 0.8103292292376812
Alpha: 66 Train: 0.7875970546404288 Test: 0.8102506271270439
Alpha: 67 Train: 0.7874194944018464 Test: 0.8101729112190272
Alpha: 68 Train: 0.7872446515365974 Test: 0.8100960680239269
Alpha: 69 Train: 0.7870724476513741 Test: 0.8100200841173542
Alpha: 70 Train: 0.7869028077311929 Test: 0.8099449461612762
Alpha: 71 Train: 0.7867356599443073 Test: 0.8098706409222323
Alpha: 72 Train: 0.786570935461244 Test: 0.8097971552870415
Alpha: 73 Train: 0.786408568286738 Test: 0.8097244762762874
Alpha: 74 Train: 0.7862484951034632 Test: 0.8096525910558199
Alpha: 75 Train: 0.7860906551265678 Test: 0.8095814869465081
Alpha: 76 Train: 0.7859349899681196 Test: 0.8095111514324316
Alpha: 77 Train: 0.785781443510649 Test: 0.8094415721676853
Alpha: 78 Train: 0.7856299617890593 Test: 0.8093727369819632
Alpha: 79 Train: 0.7854804928802397 Test: 0.8093046338850489
Alpha: 80 Train: 0.7853329867997779 Test: 0.809237251070342
Alpha: 81 Train: 0.7851873954052219 Test: 0.8091705769175341
Alpha: 82 Train: 0.7850436723053974 Test: 0.8091045999945259
Alpha: 83 Train: 0.7849017727753196 Test: 0.8090393090586789
Alpha: 84 Train: 0.78476165367629 Test: 0.8089746930574779
Alpha: 85 Train: 0.7846232733807958 Test: 0.8089107411286774
Alpha: 86 Train: 0.7844865917018646 Test: 0.8088474425999876
Alpha: 87 Train: 0.7843515698265608 Test: 0.8087847869883673
Alpha: 88 Train: 0.7842181702533255 Test: 0.8087227639989625
Alpha: 89 Train: 0.7840863567329015 Test: 0.8086613635237427
Alpha: 90 Train: 0.7839560942125867 Test: 0.8086005756398729
Alpha: 91 Train: 0.7838273487836 Test: 0.8085403906078547
Alpha: 92 Train: 0.783700087631346 Test: 0.8084807988694748
Alpha: 93 Train: 0.7835742789883859 Test: 0.80842179104558
Alpha: 94 Train: 0.7834498920899422 Test: 0.8083633579337144
Alpha: 95 Train: 0.7833268971317657 Test: 0.8083054905056329
Alpha: 96 Train: 0.783205265230225 Test: 0.8082481799047185
Alpha: 97 Train: 0.7830849683844651 Test: 0.8081914174433129
Alpha: 98 Train: 0.7829659794405157 Test: 0.8081351945999874
Alpha: 99 Train: 0.7828482720572246 Test: 0.8080795030167585

In [31]:
l2 = Ridge(alpha=7)   # within less aplha value we got better accuracy so we can select ridge algorithm
l2.fit(xtrain,ytrain)
l2.score(xtrain,ytrain),l2.score(xtest,ytest)

(0.8162882573020809, 0.8150880725612085)

In [32]:
#l2.coef_

array([ 2.31139279e+02, -3.29204695e+00, -1.90126861e+02, -1.01249352e+03,
       -6.04047656e+02,  1.71736131e+03,  3.40160377e+03,  3.91530395e+02,
        5.57861287e+02,  5.13867686e+02,  1.02968876e+02,  2.01227011e+01,
        2.13425523e+02, -2.79915768e+02])

# Elastic Net

In [33]:
en = ElasticNet(alpha=1)
en.fit(xtrain,ytrain)
en.score(xtrain,ytrain), en.score(xtest,ytest)

(0.7866253599240464, 0.8098264817256127)

In [34]:
#for i in range(1,100):
#    l3=ElasticNet (alpha=i)
#    l3.fit(xtrain,ytrain)
#    print(f"Alpha: {i} Train: {l3.score(xtrain,ytrain)} Test: {l3.score(xtest,ytest)}")

Alpha: 1 Train: 0.7866253599240464 Test: 0.8098264817256127
Alpha: 2 Train: 0.7785982256935363 Test: 0.8060357239149383
Alpha: 3 Train: 0.7741098728697711 Test: 0.8038330303232794
Alpha: 4 Train: 0.7710450291333583 Test: 0.8023305288839749
Alpha: 5 Train: 0.7687371063143833 Test: 0.8012075675535995
Alpha: 6 Train: 0.7668931957678061 Test: 0.8003179782274954
Alpha: 7 Train: 0.7653604622717018 Test: 0.7995845026702189
Alpha: 8 Train: 0.7640627321201632 Test: 0.7989624987950101
Alpha: 9 Train: 0.7629190144346731 Test: 0.7984234467905051
Alpha: 10 Train: 0.7619040267638404 Test: 0.7979480911193563
Alpha: 11 Train: 0.7609920588765116 Test: 0.7975254942341772
Alpha: 12 Train: 0.7601634437226541 Test: 0.7971420542460247
Alpha: 13 Train: 0.7594043321097714 Test: 0.7967925427385447
Alpha: 14 Train: 0.7587038337680176 Test: 0.7964714888960548
Alpha: 15 Train: 0.7580533960505055 Test: 0.7961745605956967
Alpha: 16 Train: 0.7574456236748974 Test: 0.7958954634672686
Alpha: 17 Train: 0.7568765571584644 Test: 0.7956393291880214
Alpha: 18 Train: 0.7563403297117923 Test: 0.7953973027884371
Alpha: 19 Train: 0.7558338109310031 Test: 0.7951709713032995
Alpha: 20 Train: 0.7553538085495423 Test: 0.7949547281211762
Alpha: 21 Train: 0.7548992459173389 Test: 0.7947492779120414
Alpha: 22 Train: 0.7544650430509825 Test: 0.7945521719917352
Alpha: 23 Train: 0.7540499585660765 Test: 0.7943660994241041
Alpha: 24 Train: 0.7536510721974228 Test: 0.7941871551641911
Alpha: 25 Train: 0.7532677886818848 Test: 0.7940188321292538
Alpha: 26 Train: 0.7528991277761852 Test: 0.7938572250165271
Alpha: 27 Train: 0.7525436074373606 Test: 0.7936997458691076
Alpha: 28 Train: 0.752200865317818 Test: 0.7935502359517275
Alpha: 29 Train: 0.7518696235414716 Test: 0.7934059604825052
Alpha: 30 Train: 0.7515487380100063 Test: 0.79326424102491
Alpha: 31 Train: 0.751238151635564 Test: 0.7931295559365276
Alpha: 32 Train: 0.7509368410405829 Test: 0.7929990541477396
Alpha: 33 Train: 0.7506442079656737 Test: 0.7928724649446808
Alpha: 34 Train: 0.7503594051485842 Test: 0.7927470279553013
Alpha: 35 Train: 0.7500825798406372 Test: 0.7926277369241302
Alpha: 36 Train: 0.7498129468811177 Test: 0.7925116627533839
Alpha: 37 Train: 0.7495500970271518 Test: 0.7923986225490043
Alpha: 38 Train: 0.7492936556279206 Test: 0.7922884488139857
Alpha: 39 Train: 0.7490430088421497 Test: 0.7921781969887142
Alpha: 40 Train: 0.7487984044378555 Test: 0.7920734619621366
Alpha: 41 Train: 0.7485592554095071 Test: 0.7919711513975409
Alpha: 42 Train: 0.7483252927249929 Test: 0.7918711468728019
Alpha: 43 Train: 0.7480962674104167 Test: 0.7917733385466872
Alpha: 44 Train: 0.7478719486403808 Test: 0.7916776247713366
Alpha: 45 Train: 0.747652122008615 Test: 0.7915839110905718
Alpha: 46 Train: 0.7474363930602328 Test: 0.7914889696491045
Alpha: 47 Train: 0.7472249850965504 Test: 0.7913991079721048
Alpha: 48 Train: 0.7470175092935389 Test: 0.7913109893321659
Alpha: 49 Train: 0.7468138033756808 Test: 0.7912245432202958
Alpha: 50 Train: 0.74661371537524 Test: 0.7911397035268622
Alpha: 51 Train: 0.7464171027684496 Test: 0.7910564081735135
Alpha: 52 Train: 0.7462238316990636 Test: 0.7909745987818555
Alpha: 53 Train: 0.7460337762790733 Test: 0.790894220374686
Alpha: 54 Train: 0.7458468179577331 Test: 0.7908152211061272
Alpha: 55 Train: 0.7456628449511813 Test: 0.790737552017463
Alpha: 56 Train: 0.7454817517259232 Test: 0.7906611668158835
Alpha: 57 Train: 0.7453034385302917 Test: 0.7905860216736887
Alpha: 58 Train: 0.7451278012823797 Test: 0.7905084238606379
Alpha: 59 Train: 0.7449547874990079 Test: 0.7904356914754466
Alpha: 60 Train: 0.7447842848327462 Test: 0.7903640765285114
Alpha: 61 Train: 0.7446162127846989 Test: 0.790293543807113
Alpha: 62 Train: 0.7444504948534627 Test: 0.7902240597585353
Alpha: 63 Train: 0.7442870582651183 Test: 0.7901555923784083
Alpha: 64 Train: 0.7441258337257086 Test: 0.7900881111083891
Alpha: 65 Train: 0.7439667551940163 Test: 0.7900215867422766
Alpha: 66 Train: 0.7438097596727027 Test: 0.789955991339762
Alpha: 67 Train: 0.743654787016071 Test: 0.7898912981470906
Alpha: 68 Train: 0.7435017797529111 Test: 0.7898274815240017
Alpha: 69 Train: 0.7433506829230383 Test: 0.7897645168763658
Alpha: 70 Train: 0.7432014439354083 Test: 0.7897023804453324
Alpha: 71 Train: 0.7430540124058134 Test: 0.7896410496481393
Alpha: 72 Train: 0.7429083400418316 Test: 0.7895805027357243
Alpha: 73 Train: 0.7427643805256967 Test: 0.7895207187210045
Alpha: 74 Train: 0.7426220893995508 Test: 0.7894616773954136
Alpha: 75 Train: 0.7424814239620874 Test: 0.7894033592865359
Alpha: 76 Train: 0.7423423431724336 Test: 0.7893457456187478
Alpha: 77 Train: 0.7422048075606671 Test: 0.7892888182766108
Alpha: 78 Train: 0.7420687791444296 Test: 0.7892325597707919
Alpha: 79 Train: 0.7419342213511468 Test: 0.7891769532063055
Alpha: 80 Train: 0.7418010989454026 Test: 0.7891219822528868
Alpha: 81 Train: 0.741669377961067 Test: 0.789067631117329
Alpha: 82 Train: 0.7415390256378057 Test: 0.7890138845176278
Alpha: 83 Train: 0.7414100103751028 Test: 0.788960727554672
Alpha: 84 Train: 0.7412823016491998 Test: 0.7889081459141571
Alpha: 85 Train: 0.7411558699627305 Test: 0.7888561258076298
Alpha: 86 Train: 0.7410306868200075 Test: 0.7888046537702202
Alpha: 87 Train: 0.7409067246686165 Test: 0.7887537167415961
Alpha: 88 Train: 0.7407839568560874 Test: 0.788703302048377
Alpha: 89 Train: 0.7406623575891191 Test: 0.788653397387596
Alpha: 90 Train: 0.7405419018951789 Test: 0.788603990811124
Alpha: 91 Train: 0.7404225655954224 Test: 0.7885550706586364
Alpha: 92 Train: 0.7403043251219095 Test: 0.7885066263552779
Alpha: 93 Train: 0.7401871573292453 Test: 0.7884586491048354
Alpha: 94 Train: 0.7400710404566415 Test: 0.7884111265951436
Alpha: 95 Train: 0.7399559999732346 Test: 0.7883640329448854
Alpha: 96 Train: 0.7398420022909223 Test: 0.7883173672915875
Alpha: 97 Train: 0.7397289891687762 Test: 0.7882711250367491
Alpha: 98 Train: 0.7396169415658264 Test: 0.7882252951454981
Alpha: 99 Train: 0.7395058395742748 Test: 0.788179873191414